# Generated by Django 4.1 on 2022-08-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobile_number_or_email',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='option_gender',
            new_name='optional_gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
